using WS_AsyncPaging.DTOs;
using WS_AsyncPaging.Models;

namespace WS_AsyncPaging.Services
{
    public class CustomerService : ICustomerService
    {
        private static readonly List<Customer> _customers = new();
        private static int _nextId = 1;
        static CustomerService()
        {
            _customers = Enumerable.Range(1, 500)
                .Select(i => new Customer
                {
                    Id = i,
                    Name = $"Customer {i}",
                    Email = $"customer{i}@example.com",
                    CreatedAt = DateTime.UtcNow,
                    InternalAdminNote = "Autogenerated for testing"
                })
                .ToList();

            _nextId = 501;
        }

        // Get all customers
        public Task<IEnumerable<CustomerResponse>> GetAllCustomersAsync()
        {
            var response = _customers.Select(c => MapToResponse(c));
            return Task.FromResult(response);
        }

        // Get customer by ID
        public Task<CustomerResponse?> GetCustomerByIdAsync(int id)
        {
            var customer = _customers.FirstOrDefault(c => c.Id == id);
            return Task.FromResult(customer != null ? MapToResponse(customer) : null);
        }

        // Create new customer
        public Task<CustomerResponse> CreateCustomerAsync(CreateCustomerRequest request)
        {
            var newCustomer = new Customer
            {
                Id = _nextId++,
                Name = request.Name,
                Email = request.Email,
                CreatedAt = DateTime.UtcNow
            };
            _customers.Add(newCustomer);
            return Task.FromResult(MapToResponse(newCustomer));
        }

        // Update existing customer
        public Task<bool> UpdateCustomerAsync(int id, UpdateCustomerRequest request)
        {
            var customer = _customers.FirstOrDefault(c => c.Id == id);
            if (customer == null) return Task.FromResult(false);

            customer.Name = request.Name;
            customer.Email = request.Email;

            return Task.FromResult(true);
        }

        // Delete customer
        public Task<bool> DeleteCustomerAsync(int id)
        {
            var customer = _customers.FirstOrDefault(c => c.Id == id);
            if (customer == null) return Task.FromResult(false);

            _customers.Remove(customer);
            return Task.FromResult(true);
        }

        // Helper to map Customer entity to DTO
        private CustomerResponse MapToResponse(Customer c) =>
            new CustomerResponse(c.Id, c.Name, c.Email, c.CreatedAt);
    }
}