// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkshopArtistLibrary.Data;

#nullable disable

namespace WorkshopArtistLibrary.Migrations
{
    [DbContext(typeof(WorkshopArtistLibraryDbContext))]
    [Migration("20251127095322_InitialMusicStore")]
    partial class InitialMusicStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkshopArtistLibrary.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumId"));

                    b.Property<int>("FkArtistId")
                        .HasColumnType("int");

                    b.Property<int>("FkGenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AlbumId");

                    b.HasIndex("FkArtistId");

                    b.HasIndex("FkGenreId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            FkArtistId = 1,
                            FkGenreId = 1,
                            Title = "Abbey Road"
                        },
                        new
                        {
                            AlbumId = 2,
                            FkArtistId = 2,
                            FkGenreId = 2,
                            Title = "Lemonade"
                        },
                        new
                        {
                            AlbumId = 3,
                            FkArtistId = 3,
                            FkGenreId = 3,
                            Title = "Kind of Blue"
                        },
                        new
                        {
                            AlbumId = 4,
                            FkArtistId = 4,
                            FkGenreId = 4,
                            Title = "The Marshall Mathers LP"
                        },
                        new
                        {
                            AlbumId = 5,
                            FkArtistId = 5,
                            FkGenreId = 5,
                            Title = "Requiem"
                        },
                        new
                        {
                            AlbumId = 6,
                            FkArtistId = 6,
                            FkGenreId = 6,
                            Title = "Master of Puppets"
                        },
                        new
                        {
                            AlbumId = 7,
                            FkArtistId = 7,
                            FkGenreId = 7,
                            Title = "Ring of Fire"
                        },
                        new
                        {
                            AlbumId = 8,
                            FkArtistId = 8,
                            FkGenreId = 8,
                            Title = "True"
                        },
                        new
                        {
                            AlbumId = 9,
                            FkArtistId = 9,
                            FkGenreId = 9,
                            Title = "Exodus"
                        },
                        new
                        {
                            AlbumId = 10,
                            FkArtistId = 10,
                            FkGenreId = 10,
                            Title = "Live at the Regal"
                        });
                });

            modelBuilder.Entity("WorkshopArtistLibrary.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArtistId");

                    b.HasIndex("ArtistName")
                        .IsUnique();

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            ArtistName = "The Beatles"
                        },
                        new
                        {
                            ArtistId = 2,
                            ArtistName = "Beyoncé"
                        },
                        new
                        {
                            ArtistId = 3,
                            ArtistName = "Miles Davis"
                        },
                        new
                        {
                            ArtistId = 4,
                            ArtistName = "Eminem"
                        },
                        new
                        {
                            ArtistId = 5,
                            ArtistName = "Mozart"
                        },
                        new
                        {
                            ArtistId = 6,
                            ArtistName = "Metallica"
                        },
                        new
                        {
                            ArtistId = 7,
                            ArtistName = "Johnny Cash"
                        },
                        new
                        {
                            ArtistId = 8,
                            ArtistName = "Avicii"
                        },
                        new
                        {
                            ArtistId = 9,
                            ArtistName = "Bob Marley"
                        },
                        new
                        {
                            ArtistId = 10,
                            ArtistName = "BB King"
                        });
                });

            modelBuilder.Entity("WorkshopArtistLibrary.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenreId");

                    b.HasIndex("GenreName")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Rock"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Pop"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Jazz"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Hip Hop"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Classical"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "Metal"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Country"
                        },
                        new
                        {
                            GenreId = 8,
                            GenreName = "Electronic"
                        },
                        new
                        {
                            GenreId = 9,
                            GenreName = "Reggae"
                        },
                        new
                        {
                            GenreId = 10,
                            GenreName = "Blues"
                        });
                });

            modelBuilder.Entity("WorkshopArtistLibrary.Models.Album", b =>
                {
                    b.HasOne("WorkshopArtistLibrary.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("FkArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkshopArtistLibrary.Models.Genre", "Genre")
                        .WithMany("Albums")
                        .HasForeignKey("FkGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("WorkshopArtistLibrary.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("WorkshopArtistLibrary.Models.Genre", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
